### ISSUE TITLE
freezetimers: veng timer doesnt work

### ISSUE THREAD

**Issue by xKylee** [open-osrs/runelite#1381]
when people veng, no overlay/timer appears.

happens globally, for all players including local player.

**Comment by se7enAte9** [comment]
If this is a recent issue, it's probably an unintended side effect of #1349 which changed how some of it worked. A guess would be that it's caused by the removal of `timerMap.remove(actor);` from `areAllTimersZero(Actor actor)` without updating [#L91](https://github.com/runelite-extended/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersOverlay.java#L91) of `FreezeTimersOverlay.renderOverlayFor(Graphics2D g, Actor actor)` accordingly, although I haven't tested that idea.

**Comment by Ganom** [comment]
> 
> 
> If this is a recent issue, it's probably an unintended side effect of #1349 which changed how some of it worked. A guess would be that it's caused by the removal of `timerMap.remove(actor);` from `areAllTimersZero(Actor actor)` without updating [#L91](https://github.com/runelite-extended/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersOverlay.java#L91) of `FreezeTimersOverlay.renderOverlayFor(Graphics2D g, Actor actor)` accordingly, although I haven't tested that idea.

Yeah, i feel the plugin is a bit overdone, for what it is, we can probably replace most of the code with just an object class, and it'd be much cleaner.
