### ISSUE TITLE
Readd sync by using google drive API

### ISSUE THREAD

**Issue by luna-duclos** [open-osrs/runelite#1523]
**Is your feature request related to a problem? Please describe.**
Sync was disabled as to not sync to runelite's servers, and we don't want our own server where we keep rl+ user data (for good reason).

**Describe the solution you'd like**
I suggest we integrate the google drive API to allow a user to sync to their own google drive folder, without a need for a server at all on rl+'s end.

**Describe alternatives you've considered**
We could sync to some other provider like dropbox, this isn't restricted to just google drive.

**Additional context**
None

**Comment by chrisjohnson** [comment]
It may make more sense to just document a general strategy in the wiki than implement code for this. It's not hard to do this on a per-user basis with a multitude of cloud sync options, and a general guide to "how to sync files you want to sync" would be more flexible than championing one single service and supporting it as a first class citizen in code.

That said, it's not obvious that this behavior differs from vanilla RL; I was under the impression that it functioned just like RL and didn't realize I have been going this whole time with no backup of my config. It might be nice to add a placeholder into the config panel that explains that this implied behavior isn't present in RL+ (and why that is)

**Comment by Lucwousin** [comment]
I honestly like the Google drive idea, also moves the responsibly away from us towards people's own security without being that much more of a hassle. I was about to ask why runelite chose to do it the their server way instead of own drive but that's probably cause of some http api things.

Config is something which could be improved in other ways as well like ui or config profiles
