### ISSUE TITLE
discord party plugin broken

### ISSUE THREAD

**Issue by HSJ-OSRS** [open-osrs/runelite#1677]
**Describe the bug**
Inviting or accepting an invite to a discord party doesnt work

**To Reproduce**
1. Enable discord and party plugin
2. Invite someone to your party through discord
3. Have them accept
4. See that they dont join your party

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.35-SNAPSHOT
 - Launcher version: 2.0.2-SNAPSHOT

**Additional context**
[client.log](https://github.com/runelite-extended/runelite/files/3665923/client.log)

**Comment by pklite** [comment]
this is probably happening because we never updated the runelite discord dependency package. I forked and and updated it to the newest version which is at https://github.com/runelite-extended/java-discord-rpc/packages/26816 so we would have to change the project to point to that and see if that fixes it

**Comment by chrisleee** [comment]
Did anyone ever end up following up on this and get an idea of if it is a dependency upgrade or if something else is causing the issue?
