### ISSUE TITLE
Essence pouch overlay not updating in bank

### ISSUE THREAD

**Issue by edgar1016** [open-osrs/runelite#2266]
**Describe the bug**
"show essence in pouch" from the runecrafting plugin doesn't update if you fill essence from within the bank interface.

**To Reproduce**
Fill Pouches while the bank interface is open

**Expected behavior**
Overlay updates with amount of essence currently in pouch.

**Environment (please complete the following information):**
 - Windows 10
 - 1/18/2020 Nightly Build
 - 2.0.5

**Comment by Fred4106** [comment]
Took at look at it today. The issue is that it is tracking fill/empty actions by looking at inventory changed events.
```
if (InventoryID.INVENTORY.getId() != event.getContainerId())
{
	return;
}

final Item[] items = event.getItemContainer().getItems();
```
It then counts essence from before as well as essence currently to try and guess what pouch has what. I think the best way to fix this would be to ensure an ItemContainerChanged event is sent for the inventory as well as the bank.

**Comment by xKylee** [comment]
this is the same upstream from the plugin hub. we will not be fixing this unless it omes from upstream.

due to this being on the rlhub, i removed this option from the runecraft plugin.

should you want this functionality, please use the command !rlhub in discord.
