### ISSUE TITLE
Client crash when a resizable mode setting is toggled

### ISSUE THREAD

**Issue by Galtiak** [open-osrs/runelite#2662]
**Describe the bug**
When the 'resizable mode stone buttons: 'Old School Box'' setting is toggled off and the following setting is in the `runeliteplus.properties` file:

`runelite.RESIZABLE_MINIMAP_STONES_WIDGET_preferredPosition=BOTTOM_LEFT`

It causes the client to crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings > Advanced options > Side-stones arrangement setting in game.
2. Toggle that option off (greyed out).
3. Close client.
4. Go to `runeliteplus.properties` file in the `C:\Users\User\.runelite` folder.
5. Add the following line to the top:
`runelite.RESIZABLE_MINIMAP_STONES_WIDGET_preferredPosition=BOTTOM_LEFT`
6. Open client and attempt to login.

**Expected behavior**
I am unsure how this setting came to be in my `runeliteproperties` folder to start with. It causes the OpenOSRS client to crash.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - OpenOSRS version: 3.3.6
 - Launcher version: 2.2.0

**Additional context**
```
2020-06-04 16:41:54 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 395670 out of bounds for length 384796
	at la.af(Sprite.java:686)
	at bb.kv(ScriptEvent.java:11773)
	at bz.km(ArchiveLoader.java:11691)
	at iv.io(StudioGame.java:9902)
	at iv.io(StudioGame.java:9927)
	at hy.ik(MusicPatch.java:9785)
	at client.gc(Client.java:4086)
	at client.ao(Client.java:1182)
	at br.ar(GameShell.java:362)
	at br.run(GameShell.java:316)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Devtoon** [comment]
Howsit,

I'm looking into this.

**Comment by Devtoon** [comment]
Okay so..

I have confirmed that neither the OpenOSRS client nor any of the official supported plugins add the line "runelite.RESIZABLE_MINIMAP_STONES_WIDGET_preferredPosition=BOTTOM_LEFT" to the runeliteplus.properties file. Perhaps it came from an external plugin? Are you an old Runelite user?

Now this line is funny because it takes advantage of  how the deobfuscator and injector works. So because of the OpenOSRS overlay class having access to a getter called "preferredPosition", the WidgetInfo class having access to an enum with the value "RESIZABLE_MINIMAP_STONES_WIDGET" and the values in the OverlayPosition class we can do some unintended things with the mini map.

"runelite.RESIZABLE_MINIMAP_STONES_WIDGET_preferredPosition=TOP_CENTER"

![image](https://user-images.githubusercontent.com/66264581/85814028-365f0c00-b765-11ea-9a1b-abb297f3c483.png)

"runelite.RESIZABLE_MINIMAP_STONES_WIDGET_preferredPosition=ABOVE_CHATBOX_RIGHT"

![image](https://user-images.githubusercontent.com/66264581/85813930-e41deb00-b764-11ea-9b13-488e5e9abbda.png)
![image](https://user-images.githubusercontent.com/66264581/85813958-fe57c900-b764-11ea-9b70-dc5aa30bee57.png)

But now because this is something that was never intended we start getting unexpected results.

"runelite.RESIZABLE_MINIMAP_STONES_WIDGET_preferredPosition=TOP_LEFT"

![image](https://user-images.githubusercontent.com/66264581/85814477-52af7880-b766-11ea-9f86-b14a40a56000.png)

"runelite.RESIZABLE_MINIMAP_STONES_WIDGET_preferredPosition=DYNAMIC"

I actually thought this was really going to pick a random position but nah..

![image](https://user-images.githubusercontent.com/66264581/85814663-c05ba480-b766-11ea-8ac2-3ce1e8958e16.png)

And obviously as one would expect unintended results can cause chaos.

"runelite.RESIZABLE_MINIMAP_STONES_WIDGET_preferredPosition=TOOLTIP"

![image](https://user-images.githubusercontent.com/66264581/85815468-c81c4880-b768-11ea-8f2b-5017e880e1ad.png)

The hilarious thing is I don't even have a XP tracker plugin installed so I have no idea what's going on here because now we are getting down to a bytecode level.

Which brings us to "runelite.RESIZABLE_MINIMAP_STONES_WIDGET_preferredPosition=BOTTOM_LEFT" which actually breaks the  Runescape client and not the OpenOSRS client. This is because the Runescape client is trying to put the mini map in a position that is intended for Overlays drawn by the OpenOSRS client but exceeds boundary restrictions of where the mini map can be on a bytecode level within the Runescape client.

So there is no way of fixing this because there is nothing to fix. However I can assure you that you can safely remove that line from your runeliteplus.properties file.

**Comment by Lucwousin** [comment]
This has nothing to do with the injector. The `preferredPosition` is set by alt-click dragging the overlay onto a drag zone (OverlayManager line 333)

**Comment by Lucwousin** [comment]
This is caused by moving the minimap, switching to fixed mode, then resizing the client so the minimap doesn't fit in the client anymore (when switching back), then switching back to resizable.

There's not really any good way to stop this from happening, but if you fullscreen the client and reset the minimaps' position (alt + right-click), you can resize the resizable client to any size your heart desires again.
