### ISSUE TITLE
Script assembler 

### ISSUE THREAD

**Issue by Lucwousin** [open-osrs/runelite#2665]
Script assembler currently is hacked into gradle in the worst way possible.

* It runs way too often because of not declaring outputs and inputs.
* It outputs files into source directories, meaning a clean build will not have the updated scripts, you gotta build again.
* It was designed with maven in mind, it should be a gradle plugin.
* (Optional) It could do with a source update feature, comparing new revision scripts to edited scripts and automatically update the source. This currently takes a bit of time on updates.

**Comment by swazrgb** [comment]
#2679 addressed:

* It runs way too often because of not declaring outputs and inputs.

* It outputs files into source directories, meaning a clean build will not have the updated scripts, you gotta build again.

Ideally it should still be converted to a proper gradle plugin, but this requires splitting the cache module out of this build.
