### ISSUE TITLE
ZULRAH HELPER improvements

### ISSUE THREAD

**Issue by rev-mann** [open-osrs/runelite#611]
1) Include countdown timers for each phase (above zulrah's head is a good place)

2) Instead of having what to pray and what phase is next at the bottom right corner of the screen, could be integrated so it is part of the map?

Feels more intuitive compared to having to glance at the bottom corner of the screen

This is what it looks like taken from Lyzrdlite, I believe the code is online elsewhere too:
[https://imgur.com/qw4wXy8](url)

3) If the code for this plugin already exists online, could we have an option to choose which plugin we prefer in the 'Zulrah Helper' settings?

**Comment by rev-mann** [comment]
im not sure why the imgur link doesn't work though

**Comment by xperiaclash** [comment]
yes I also prefer lyzrd's implementation , code is opensource on lyzrd, wonder what the rl+ devs have to say tbh

**Comment by rev-mann** [comment]
would really love to see it added, even if it is not replaced... the option to choose either version via settings/slider would be awesome :D

**Comment by p00boy** [comment]
It was originally like that in the beginning - then it was replaced by the current implementation since it was deemed better by the majority. My only issue with the helper on lyzrdlite is that it tells you to stand on the poison in one of the rotations, as well as telling you to stand on some spots that are sub optimal. Layouts and highlights are minimal and concise though, which is nice.

**Comment by xperiaclash** [comment]
yes the minimality is what's good about it, also jad phase iirc works too

**Comment by Ganom** [comment]
It was replaced because it was a cluster fuck of a plugin, we have been very busy with getting injector 100% operational, when everything is settled down, we will go back and look over the zulrah plugin.

**Comment by NotTeeZee** [comment]
A few suggestions for new zulrah plugin:
1) Ability to toggle on/off the pattern displayed (e.g. Pattern D) bottom-right in configuration
2) Tick timer to show how long till next phase
3) In Melee phase, show where to stand and when to switch to another tile  to dodge the melee attack (maybe with a ticket timer too?)
4) Show melee phase as red instead of orange at the bottom-right
5) Show where Zulrah will be next phase, and what to pray against it (much like previous plugin: https://imgur.com/qw4wXy8)
6) Potentially show where venom gas will be next phase
7) Show when to disable prayer if its enabled (much like previous plugin)
8) The ability to drag the overlays much like RuneLite's overlays (with this, suggestion#1 would become less interesting)
9) Ability (configuration) to swap the 'Attack' option to 'Walk here' to never attack snakelings (ring of recoil/suffering deals with this)
10) Indicate Jad phase more clear (its currently the same color orange, but with a green zulrah model), maybe with text 'JAD PHASE' on top of the npc in addition to suggestion #5
