### ISSUE TITLE
Pile Finder for Clanning

### ISSUE THREAD

**Issue by Needbourbon** [open-osrs/runelite#967]
A Pile Finder would be an amazing addition. The way it would work is:
-If 3+ clan members are attacking the same target, then that target's name will be highlighted with the user's chosen font color.
-If more than 1 person is being attacked by 3+ clan members, then the target currently being attacked by the most clan members, will have their name highlighted. Only 1 name will be highlighted at any given moment.

I know the caller option exists, but sometimes there's situations where this would be extremely beneficial.  Sometimes Clans just PK at revs, and there's no rank on, so it's just a group of guys pking. You log into a world, and everyone starts hitting random people, with this plugin you would be able to instantly see who the most people are piling, and call that pile out to them in TeamSpeak.  I know it's not the best example, but one other situation is when callers die, the user person can see who is being prioritized, and call out that name because they see it highlighted, creating a more efficient situation for winning the fight. 

I've seen another client utilize this feature, and it's been called OP in my clan, and in SharkBrew before. It would be amazing to see it brought to Runelite. It's the only feature I really miss.

**Comment by f0rmatme** [comment]
pile indicators is in the client
![nsjV45C9kBdflej](https://user-images.githubusercontent.com/38226001/61008573-befe5580-a324-11e9-8738-5413a74e8460.png)

**Comment by Kyleeld** [comment]
@f0rmatme thats a different pile finder.

**Comment by jjfishbeck44** [comment]
Also that pile indicator is very messy/distracting imo. But I was just discussing about a clan calling plugin last night to my boy Tom. 

I think it was be nice to have it show a flashing tile square under the person that’s being attacked by the highest amount of cc players. As well as the flashing tile under the player we are targeting, I think that in the right click options only the top line (“attack” & RSN name ) should be changed to a different color. 

This solves 2 issues I have with the current plugins available. So when I’m warring I usually need to turn off the pile indicator because it’s ugly and kind laggy? But to be fair, this plugin is only really useful for alerting you when a clan is logging in on your world of d bow rushing or something like that. 

But back to the issues, is it’s already hard enough to first listen to the calls on teamspeak, then find the location of the target, then find the name when there legit is 200 ppl in a 8 tile area. 

Another idea, can we have a option be an added to entity hider? A lot of the times, at like revs entrance when clans are pussy slapping each other in singles and multi, i wanna be able to use entity hider to ONLY show players who are attacking me and see my account itself only. Also this would be beneficial when you get tbed by a max main clan deep wildly and they are all switching off attacking you.  I don’t wanna see the people following me, just attacking me

**Comment by jjfishbeck44** [comment]
Lmk if Any part needs clarification as I CbA to proof read it as it was kinda a rant message. :)
